from .combat.combat import OSRSCombat
from .cooking.brew_wines import POSRSBREWWINES
from .cooking.cooking_al_kharid import POSRSCOOKINGALKHARID
from .cooking.crafting_dough import POSRSCRAFTINGDOUGH
from .crafting.smelting_jewellery_edgevill import OSRSSmeltingJewelleryEdgeVill
from .fishing.fly_and_cooking import OSRSFLYCooking
from .fishing.net_fishing import OSRSNetFishing
from .fletching.making_bows import POSRSMAKEBOWS
from .fletching.making_headless_arrow import POSRSHEADLESSARROW
from .magic.high_alch import OSRSHIGHALCH
from .mining.motherload_mine import POSRSMotherLoadMiner
from .mining.power_mining import POSNRPowerMiner
from .money_making.items_maker import POSRSITEMSMAKE
from .money_making.make_admiral_pies import POSRSMAKEADMIRALPIES
from .prayer.Camoda_Fish_Offering import POSRSCamodaFishOffering
from .theiving.pick_pocket_npc import POSRSPICKPOCKET
from .theiving.stall_power import POSRSPICKSTALL
from .woodcutting.PWoodcuter import POSNRWoodcutting
